### ISSUE TITLE
docker-compose.yaml image number hasn't been updated 

### ISSUE THREAD

**Issue by vwfast** [aleksanderbl29/docker-pihole-unbound#42]
For those that rely on the docker-compose.yaml file for installation/updating, the image number hasn't been updated to reflect the newly updated image.

Current:
image: aleksanderbl/pihole-unbound:2024.01.0

Update:
image: aleksanderbl/pihole-unbound:2024.02.0

**Comment by aleksanderbl29** [comment]
I have now fixed this
