### ISSUE TITLE
Env $PIHOLE_VERSION

### ISSUE THREAD

**Issue by afreisinger** [aleksanderbl29/docker-pihole-unbound#56]
Hi !, very good work! 
For some reason the Dockerfile does not receive $PIHOLE_VERSION as an argument? You get it in the autobuild.yml. Regards. Adrian

**Comment by aleksanderbl29** [comment]
Hi @afreisinger !
Thank you for making me aware of this. I thought i had removed the build arg in all the places that it was left.

The pihole_version is hardcoded in the Dockerfile and it is updated in there when a new update published. I did this to not have to rely on the scheduled github actions and instead publish a new image 1) when available and 2) when I have had the chance to test it in my homelab.

**Comment by afreisinger** [comment]
The logic is perfect !
