### ISSUE TITLE
Unbound is not updated

### ISSUE THREAD

**Issue by fidoboy** [aleksanderbl29/docker-pihole-unbound#59]
Current bundled version is 1.17.1 and the latest one is 1.20.0. Why?

**Comment by aleksanderbl29** [comment]
The pihole currently based on bullseye-slim as far as i know.
The latest version of unbound in apt-repos for debian is 1.17.1.

In response to #40 I have created a release [aleksanderbl/pihole-unboynd:dev-45](https://hub.docker.com/layers/aleksanderbl/pihole-unbound/dev-45/images/sha256-6b85bf23142dc2e79c704455da714de3f032db956011faf94ae6deb8754d745d?context=explore) that installs the latest version from the trixie repo, which currently is [v.1.20.0-1](https://packages.debian.org/trixie/unbound)

I plan on making a release alongside the stable one that installs the newest version of unbound from either sid or trixie, but I haven't gotten around to it yet.
