### ISSUE TITLE
Noobie Question - How to confirm Unbound functionality?

### ISSUE THREAD

**Issue by SolarSupremacy** [aleksanderbl29/docker-pihole-unbound#64]
I have your container setup on my home server and pihole is running just fine.

However, I'm not feeling the benefits of unbound and don't know how to check if unbound is actually working.

As a noobie, the install steps in your repo's readme were a bit unclear so I wasn't sure. If you help me understand what I'm doing and how to make sure docker is setup, I wouldn't mind reviding the readme to make a bit more clear to new users like me. =)

These are my pihole DNS configurations:
![image](https://github.com/user-attachments/assets/b0241b1a-169b-49d9-906a-4a46be96a2f4)
![image](https://github.com/user-attachments/assets/3536effc-8551-4abd-b219-b0dfdf1b9caf)
I don't think I've done anything to unbound itself so it should just be what it was when it was installed.

Thanks for the help!

**Comment by aleksanderbl29** [comment]
Hi @SolarSupremacy !

I completely agree that the instructions aren't the clearest - Just haven't come around to properly writing install instructions. Would totally be open to collaborating on a proper step by step guide.

On to your issue:

You should remove the checkmarks from the Quad9 dns servers and set Custom 1 to `127.0.0.1#5335`. Then all should be working.

To check that unbound is functioning properly you can `docker exec -it bash pihole` into your container (with pihole being the container name) and run the following three commands. 

```{bash}
dig fail01.dnssec.works @127.0.0.1 -p 5335
dig dnssec.works @127.0.0.1 -p 5335
dig pi-hole.net @127.0.0.1 -p 5335
```

I usually follow the official [pihole-unbound documentation](https://docs.pi-hole.net/guides/dns/unbound/#test-validation) when debugging. They could probably be useful for writing the how-to.

If or when you feel comfortable enough to contribute with some better documentation, I would be happy to include it and provide my thoughts on it as well.

Let me know how it goes!

**Comment by aleksanderbl29** [comment]
![Skærmbillede 2024-08-20 kl  20 38 40](https://github.com/user-attachments/assets/ec8aad76-8afb-4e6e-906d-d82a97577421)

For the commands I provided above, the results should look something like this

**Comment by SolarSupremacy** [comment]
I think the command should be `docker exec -it pihole bash`.

Also, my heart sank when I ran `dig fail01.dnssec.works @127.0.0.1 -p 5335` until I realized that's what's _supposed_ to happen! By running `unbound-control stats_noreset`, I can see that it's getting queries. I think my speed of re-loading a website is significantly faster than the first time I visit which also seems to be evidence of it working.

I've got another project I need to work on tonight but I definitely wouldn't mind contributing since this is very helpful! I would like to make a contribution that could have saved past-me and future similar-to-me-s. Haha.

_Off topic..._

Before I found this project, I was setting up pihole and unbound in separate containers and ran into the whole `macvlan` shenanigans. Macvlan seems really cool and convenient! Perfect for hosting multiple webservers (home assistant, pihole, etc.) all on port 80 with separate IPs... except for the fact that the host system (running docker) cannot access it's own macvlan containers... The containers could talk to each other (and I think I had pihole and unbound running) but the host PC couldn't access pihole's macvlan... Very frustrating.

I'm sure some additional info in the readme would suffice for getting it setup, but I'm wondering if the docker-compose can be modified in some way to change pihole's config (either via command or including config files) to default to the proper upstream DNS config.

**Comment by aleksanderbl29** [comment]
> I think the command should be `docker exec -it pihole bash`.

Yes, absolutely - I write it the wrong way around all the time.
Great to hear that it's working for you.

I went down a similar path as you with the separate deployments and found the project that I've forked here. 

> but I'm wondering if the docker-compose can be modified in some way to change pihole's config (either via command or including config files) to default to the proper upstream DNS config.

For my deployment I think I have passed the upstream dns as a environment-var in the docker-compose. I now see, also, that the compose file in this repo probably needs some cleanup. Will add that to my to-do.

**Comment by aleksanderbl29** [comment]
> Also, my heart sank when I ran `dig fail01.dnssec.works @127.0.0.1 -p 5335` until I realized that's what's _supposed_ to happen!

This would probably be a good idea to include in the readme when recommending the command for testing

**Comment by SolarSupremacy** [comment]
I _think_ I just submitted a pull request with a revised readme. Never done that before (I use GitHub more like Google Drive... xP).

I tried to add more information to answer questions I had back when I was going through the process.

**Comment by SolarSupremacy** [comment]
Nope. I have no idea what I did. I think I pulled into my own repository for no reason and then submitted a pull request to a different repository...

Instead, [here](https://github.com/SolarSupremacy/docker-pihole-unbound/blob/main/README.md) is my revised readme. Haha

Thanks for the help!

**Comment by aleksanderbl29** [comment]
Closing this issue. Please re-comment if there is anything further :)
